[package]
authors = ["Rahix <h.w.seiler@gmx.de>"]
name = "coriolis-sim"
version = "0.1.0"

[dependencies]
nalgebra = "0.13.0"
sfml = "0.14.0"

[dependencies.eagre-ecs]
git = "https://github.com/Rahix/eagre-ecs"
